version: '3'

services:

    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkinscompose
        ports:
            - "50000:50000"
            - "8880:8080"
        volumes: 
            - ../volumes/jenkins:/var/jenkins_home
        networks: 
            - docker_network

    ubuntu_slave:
        container_name: ubuntucompose
        environment:
          - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        volumes: 
            - /var/run/docker.sock/:/var/run/docker.sock
        build: 
            context: ../dockerfiles/slave
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/jenkins-agent.jnlp -secret cb775d59eb799dbb522e130553f7b90913a1a14811a3977939a3072fcebf57a9 -workDir "/home/"
        depends_on: 
            - jenkins
        networks: 
            - docker_network

    selenium_hub:
        image: selenium/hub
        container_name: selenium-hubcompose
        ports: 
            - "4444:4444"
        networks:
            - docker_network

    selenium-node:
        image: selenium/node-firefox
        container_name: firefoxcompose
        depends_on: 
            - selenium_hub
        environment: 
            - HUB_HOST=selenium-hubcompose
            - HUB_PORT=4444
        networks:
            - docker_network

    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactorycompose
        volumes: 
            - ../volumes/artifactory:/var/opt/jfrog/artifactory
        ports: 
            - "8081:8081"
            - "8082:8082"
        networks:
            - docker_network

networks:
    docker_network:
        driver: bridge